### ISSUE TITLE
`Cilfacade.split_anoncomp_name` exception for coreutils programs

### ISSUE THREAD

**Issue by nathanschmidt** [goblint/analyzer#1171] opened 2023-09-16 13:06 UTC
When running Goblint on the coreutils programs of the bench repository, it crashes with the following message: `Fatal error: exception Invalid_argument("Cilfacade.split_anoncomp_name")`.

The following is also printed:
```
[Error][Analyzer] About to crash!

:-1: Warning: Incompatible declaration for pthread_mutex_init (from .goblint/preprocessed/pthread.i(1)).
 Previous was at /usr/include/pthread.h:733 (from .goblint/preprocessed/tail_comb.i (0)) 
        Failed assumption that pthread_mutex_t and pthread_mutex_t are isomorphic 
        Failed assumption that union __anonunion_pthread_mutex_t_11 and union __anonunion_pthread_mutex_t_335460617 are isomorphic (different number of fields in __pthread_mutex_s and __pthread_mutex_s: 7 != 8.)
union __anonunion_pthread_mutex_t_11 {
   struct __pthread_mutex_s __data ;
   char __size[40] ;
   long __align ;
};

union __anonunion_pthread_mutex_t_335460617 {
   struct __pthread_mutex_s __data ;
   char __size[40] ;
   long __align ;
};
```

I went back and found that the crash doesn't occur for commit goblint/analyzer@73eaa698309e23a6ed29d1c992b9a3cd655a7f2d, so I suppose something that has been introduced later could be responsible.

**Comment by mrstanb** [comment] 2023-09-16 14:48
I also noticed that in the SV-COMP Memory Safety benchmark runs, there were a few exceptions due to `Cilfacade.split_anoncomp_name`. I haven't checked in further detail what the cause is, but I can look into it if necessary.

**Comment by sim642** [comment] 2023-09-18 08:13
I'll have a look. This is just used to hide the contents of some pthread implementation detail structures, so there wouldn't be any problem just ignoring the case where this regex fails to match. Although I'm surprised that it does. Maybe something to do with CIL-merged programs, which these sv-benchmarks folders seem to have.

**Closed** 2023-09-18 08:32 UTC
Labels: bug, benchmarking
