### ISSUE TITLE
Unsoundness in SV-COMP Prerun

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#141] opened 2020-11-23 07:58 UTC
In the following cases we were unsound for the pre-runs:

- [x] bitvector/s3_clnt_3.BV.c.cil-2a.yml
  - Turns into a timeout with #121
- [x] float-benchs/nan_double.yml
  - Still happens after merging #121
- [x] float-benchs/nan_float.yml
  - Still happens after merging #121
- [x] float-newlib/double_req_bl_1210.yml
  - Still happens after merging #121
- [x] float-newlib/float_req_bl_1210.yml
  - Still happens after merging #121
- [x] ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko.cil.yml
  - Still happens after merging #121 
  - See #143 
- [x] pthread-driver-races/char_generic_nvram_read_nvram_write_nvram.yml
  - Still happens after merging #121 
  - See #143
- [x] goblint-regression/28-race_reach_45-escape_racing.yml
  - Still happens after merging #121 
  - See #142 
- [x]  ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--staging--lustre--lustre--llite--llite_lloop.ko-entry_point.cil.out.yml
  - Fixed by https://github.com/goblint/analyzer/commit/7d0fbeefba2cdcaa66c1b53b8d2cc05827189f8f and `unknown` result on current master

**Comment by michael-schwarz** [comment] 2020-11-23 07:59
I'll check which of these are problematic also after merging #121

**Comment by michael-schwarz** [comment] 2020-11-23 08:27
The first two are variations of this:

~~~C
/* Assertion can be violated because uninitialized doubles can be NaN.  */

int main()
{
  double x;
  x = __VERIFIER_nondet_double();

  __VERIFIER_assert(x==x);
  return 0;
}
~~~

**Comment by sim642** [comment] 2020-11-23 08:38
Right now on master the last one gives `unknown` for me. This was fixed by https://github.com/goblint/analyzer/commit/7d0fbeefba2cdcaa66c1b53b8d2cc05827189f8f. Does #121 break it again or what?

**Comment by michael-schwarz** [comment] 2020-11-23 10:13
> Right now on master the last one gives `unknown` for me. This was fixed by [7d0fbee](https://github.com/goblint/analyzer/commit/7d0fbeefba2cdcaa66c1b53b8d2cc05827189f8f). Does #121 break it again or what?

It doesn't I was running with the wrong property :facepalm: 
`CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )`

**Comment by sim642** [comment] 2020-11-23 10:47
Annoyingly, pthread-driver-races/char_generic_nvram_read_nvram_write_nvram.yml also is because of `var_eq` issues, specifically the following:
```c
 *ppos = i;
 __VERIFIER_assert(*ppos == i);
```

`var_eq` makes the assertion go through while it actually doesn't, because `ppos` points to a malloc-ed memory, which is shared between threads.

**Comment by michael-schwarz** [comment] 2020-11-23 12:46
> Annoyingly, pthread-driver-races/char_generic_nvram_read_nvram_write_nvram.yml also is because of `var_eq` issues, specifically the following:
> 
> ```c
>  *ppos = i;
>  __VERIFIER_assert(*ppos == i);
> ```
> 
> `var_eq` makes the assertion go through while it actually doesn't, because `ppos` points to a malloc-ed memory, which is shared between threads.

This is strange, shouldn't 

https://github.com/goblint/analyzer/blob/9c5d9b0e598e1315741d636fab115c3d7bf9ee8a/src/analyses/varEq.ml#L364-L366

prevent any global variables from ending up in these equivalence classes? And all malloced memory is generated via ` Goblintutil.create_var (makeGlobalVar name voidType)`

**Comment by sim642** [comment] 2020-11-23 12:52
`ppos` itself is a local variable which may point to the global malloc variable. The current `Exp.is_global_var` doesn't consider that at all. I have a fix for this that I haven't pushed yet but will in a moment.

I've been trying to add a minimal regression test for this but somehow the original program has slightly different behavior and I can't understand how it is possible: the global `whoop_loff_t`, which is what `ppos` is assigned from, somehow doesn't contain `NULL` anymore even though it gets zero-initialized to that.

**Closed** 2020-11-24 10:00 UTC
Labels: sv-comp, unsound
