### ISSUE TITLE
Privatizations unsound when threadflag analysis deactivated

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#860] opened 2022-10-19 07:08 UTC
In #859 one of the autotune unsoundness cases was caused by autotune deactivating the threadflag analysis. A minimized TODO test is added here: https://github.com/goblint/analyzer/pull/859/commits/505b66949e488060daf82413a399b328d05b4ebc.

The problem is, when threadflag is deactivated, `EnterMultithreaded` event is never emitted and thus privatizations don't correctly publish initial values, in that particular case to `MUTEX_INITS`. I'm not sure which privatizations (both base and apron) are affected, possibly all non-trivial ones.

**Comment by michael-schwarz** [comment] 2023-07-11 18:58
I was unable to reproduce this issue with the newer versions of Goblint. Closing for now.

**Closed by michael-schwarz** 2023-07-11 18:58 UTC
Labels: bug, unsound
