### ISSUE TITLE
Goblint crashes with `Lattice.Uncomparable` on some runs on `zstd`

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#961] opened 2022-12-26 16:46 UTC
An exception `Goblint_lib.Lattice.Uncomparable` occurs when running Goblint on few commits on the `zstd` repository. 

Parent commit: `4b9d1dd9ffc882ff9ac57e2363a411591a27b886`

Command line:
```
./goblint --conf conf/custom/zstd-race.json -v --disable incremental.load --enable incremental.save ../zstd
```

Child commit: `8296be4a0a25b6e2f74f1cdd7bd4ae04981f6a45`
```
./goblint --conf conf/custom/zstd-race.json -v --enable incremental.load --disable incremental.save ../zstd
```

This [script](https://github.com/goblint/bench/blob/294cf9a1dc062347d92df0cfc8eece0320420513/scripts/incremental/build/build_compdb_zstd.sh) has to be executed before each analysis to prepare the compile db.
<details>
<summary>Stack trace</summary>

```
Fatal error: exception Goblint_lib.Lattice.Uncomparable
Marked with transfer function at zstd/lib/compress/zstd_compress.c:1744:5-1744:34
Marked with transfer function at zstd/lib/compress/zstd_compress.c:1964:27-1964:184
Marked with transfer function at zstd/lib/compress/zstd_compress.c:2062:27-2062:123
Marked with transfer function at zstd/lib/compress/zstd_compress.c:2191:9-2192:57
Marked with transfer function at zstd/lib/compress/zstd_compress.c:4512:9-4512:85
Marked with transfer function at zstd/lib/compress/zstd_compress.c:4547:5-4551:59
Marked with transfer function at zstd/lib/compress/zstdmt_compress.c:698:22-698:159
Marked with transfer function at zstd/lib/common/pool.c:94:13-94:37
Marked with transfer function at zstd/lib/common/pool.c:151:17-151:41
Marked with transfer function at zstd/lib/compress/zstdmt_compress.c:941:7-941:64
Marked with transfer function at zstd/lib/compress/zstdmt_compress.c:963:5-963:70
Marked with transfer function at zstd/lib/compress/zstd_compress.c:5591:13-5591:105
Marked with transfer function at zstd/lib/compress/zstd_compress.c:5669:27-5669:99
Marked with transfer function at zstd/programs/fileio.c:1287:13-1287:89
Marked with transfer function at zstd/programs/fileio.c:1467:13-1467:127
Marked with transfer function at zstd/programs/fileio.c:1582:5-1582:106
Marked with transfer function at zstd/programs/fileio.c:1663:5-1663:105
Marked with transfer function at zstd/programs/fileio.c:1730:15-1730:115
Marked with transfer function at zstd/programs/zstdcli.c:1469:13-1469:143
Raised at Goblint_lib__Lval.Offset.merge in file "src/cdomains/lval.ml", line 138, characters 11-37
Called from Goblint_lib__Lval.Offset.merge in file "src/cdomains/lval.ml", line 137, characters 58-73
Called from Goblint_lib__Lval.NormalLat.merge in file "src/cdomains/lval.ml", line 377, characters 72-90
Called from Goblint_lib__MapDomain.PMap.long_map2.f in file "src/domains/mapDomain.ml", line 154, characters 33-43
Called from Stdlib__Map.Make.merge in file "map.ml", line 398, characters 44-63
Called from Stdlib__Map.Make.merge in file "map.ml", line 395, characters 64-79
Called from Stdlib__Map.Make.merge in file "map.ml", line 398, characters 25-40
Called from Goblint_lib__MapDomain.MapBot.join in file "src/domains/mapDomain.ml" (inlined), line 402, characters 13-37
Called from Goblint_lib__AddressDomain.AddressSet.join in file "src/cdomains/addressDomain.ml", line 41, characters 12-20
Called from Stdlib__Map.Make.fold in file "map.ml", line 321, characters 19-42
Called from Goblint_lib__Base.MainFunctor.reachable_from_value.(fun) in file "src/analyses/base.ml", line 522, characters 68-116
Called from Stdlib__Map.Make.fold in file "map.ml", line 321, characters 19-42
Called from Stdlib__Map.Make.fold in file "map.ml", line 321, characters 26-41
Called from Goblint_lib__Base.MainFunctor.reachable_from_address in file "src/analyses/base.ml", line 533, characters 14-101
Called from Goblint_lib__Base.MainFunctor.reachable_vars.visit_and_collect in file "src/analyses/base.ml", line 554, characters 17-55
Called from Stdlib__Map.Make.fold in file "map.ml", line 321, characters 19-42
Called from Goblint_lib__Base.MainFunctor.reachable_vars in file "src/analyses/base.ml", line 555, characters 22-62
Called from Goblint_lib__Base.MainFunctor.make_entry.(fun) in file "src/analyses/base.ml", line 2423, characters 50-122
Called from Goblint_lib__Base.MainFunctor.enter in file "src/analyses/base.ml", line 2438, characters 16-38
Called from Goblint_lib__MCP.MCP2.enter.f in file "src/analyses/mCP.ml", line 490, characters 55-73
Called from BatList.map.loop in file "src/batList.mlv", line 242, characters 28-33
Called from BatList.map in file "src/batList.mlv", line 245, characters 4-12
Called from Goblint_lib__MCP.MCP2.enter in file "src/analyses/mCP.ml", line 492, characters 14-42
Called from Goblint_lib__Constraints.WidenContextLifterSide.enter in file "src/framework/constraints.ml", line 368, characters 4-31
Called from Goblint_lib__Constraints.PathSensitive2.fold'.k in file "src/framework/constraints.ml", line 1155, characters 17-37
Called from BatSet.Concrete.fold in file "src/batSet.mlv", line 316, characters 35-56
Called from Goblint_lib__Constraints.DeadCodeLifter.lift_fun in file "src/framework/constraints.ml", line 410, characters 13-29
Called from Goblint_lib__Constraints.HashconsLifter.enter in file "src/framework/constraints.ml", line 70, characters 50-77
Called from Goblint_lib__Constraints.FromSpec.tf_normal_call in file "src/framework/constraints.ml", line 640, characters 16-37
Called from BatList.filter_map.loop in file "src/batList.mlv", line 548, characters 12-15
Called from BatList.filter_map in file "src/batList.mlv", line 554, characters 2-14
Called from Goblint_lib__Constraints.FromSpec.tf_proc in file "src/framework/constraints.ml", line 693, characters 15-53
Called from Goblint_backtrace.protect in file "src/util/backtrace/goblint_backtrace.ml", line 29, characters 8-15
Re-raised at Goblint_backtrace.protect in file "src/util/backtrace/goblint_backtrace.ml", line 37, characters 4-50
Called from BatList.fold_left2 in file "src/batList.mlv", line 665, characters 39-54
Called from Stdlib__Fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__Fun.protect in file "fun.ml", line 38, characters 6-52
Called from BatList.map in file "src/batList.mlv", line 244, characters 23-28
Called from Goblint_lib__Constraints.FromSpec.system.tf in file "src/framework/constraints.ml", line 778, characters 27-47
Called from Goblint_lib__Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 1012, characters 4-105
Called from Goblint_lib__Td3.Base.solve.solve in file "src/solvers/td3.ml", line 301, characters 14-39
Called from Goblint_lib__Td3.Base.solve.simple_solve in file "src/solvers/td3.ml", line 355, characters 46-59
Called from Goblint_lib__Td3.Base.solve.eval in file "src/solvers/td3.ml", line 383, characters 18-36
Called from BatInnerPervasives.(%) in file "src/batInnerPervasives.mlv" (inlined), line 77, characters 20-25
Called from Goblint_lib__Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 1012, characters 7-17
Called from Goblint_lib__Constraints.FromSpec.tf in file "src/framework/constraints.ml", line 742, characters 15-25
Called from Stdlib__Fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__Fun.protect in file "fun.ml", line 38, characters 6-52
Called from BatList.map in file "src/batList.mlv", line 244, characters 23-28
Called from Goblint_lib__Constraints.FromSpec.system.tf in file "src/framework/constraints.ml", line 778, characters 27-47
Called from Goblint_lib__Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 1012, characters 4-105
Called from Goblint_lib__Td3.Base.solve.solve in file "src/solvers/td3.ml", line 301, characters 14-39
Called from Goblint_lib__Td3.Base.solve.simple_solve in file "src/solvers/td3.ml", line 355, characters 46-59
Called from Goblint_lib__Td3.Base.solve.eval in file "src/solvers/td3.ml", line 383, characters 18-36
Called from BatInnerPervasives.(%) in file "src/batInnerPervasives.mlv" (inlined), line 77, characters 20-25
Called from Goblint_lib__Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 1012, characters 7-17
Called from Goblint_lib__Constraints.FromSpec.tf in file "src/framework/constraints.ml", line 742, characters 15-25
Called from Stdlib__Fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__Fun.protect in file "fun.ml", line 38, characters 6-52
Called from BatList.map in file "src/batList.mlv", line 244, characters 23-28
Called from Goblint_lib__Constraints.FromSpec.system.tf in file "src/framework/constraints.ml", line 778, characters 27-47
Called from Goblint_lib__Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 1012, characters 4-105
Called from Goblint_lib__Td3.Base.solve.solve in file "src/solvers/td3.ml", line 301, characters 14-39
Called from Goblint_lib__Td3.Base.solve.simple_solve in file "src/solvers/td3.ml", line 355, characters 46-59
Called from Goblint_lib__Td3.Base.solve.eval in file "src/solvers/td3.ml", line 383, characters 18-36
Called from BatInnerPervasives.(%) in file "src/batInnerPervasives.mlv" (inlined), line 77, characters 20-25
Called from Goblint_lib__Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 1012, characters 7-17
Called from Goblint_lib__Constraints.FromSpec.tf in file "src/framework/constraints.ml", line 742, characters 15-25
Called from Stdlib__Fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__Fun.protect in file "fun.ml", line 38, characters 6-52
Called from BatList.map in file "src/batList.mlv", line 244, characters 23-28
Called from Goblint_lib__Constraints.FromSpec.system.tf in file "src/framework/constraints.ml", line 778, characters 27-47
Called from Goblint_lib__Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 1012, characters 4-105
Called from Goblint_lib__Td3.Base.solve.solve in file "src/solvers/td3.ml", line 301, characters 14-39
Called from Goblint_lib__Td3.Base.solve.simple_solve in file "src/solvers/td3.ml", line 355, characters 46-59
Called from Goblint_lib__Td3.Base.solve.eval in file "src/solvers/td3.ml", line 383, characters 18-36
Called from BatInnerPervasives.(%) in file "src/batInnerPervasives.mlv" (inlined), line 77, characters 20-25
Called from Goblint_lib__Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 1012, characters 7-17
Called from Goblint_lib__Constraints.FromSpec.tf in file "src/framework/constraints.ml", line 742, characters 15-25
Called from Stdlib__Fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__Fun.protect in file "fun.ml", line 38, characters 6-52
Called from BatList.map in file "src/batList.mlv", line 244, characters 23-28
``` 

</details>

**Comment by sim642** [comment] 2022-12-27 14:16
The exception is from joining/etc of offsets here:
https://github.com/goblint/analyzer/blob/c7f557d73e13a23efd63e8736574fe9f9ca956fb/src/cdomains/lval.ml#L127-L138
The odd thing is that with the new address domain partitioning, there shouldn't be any way for different offset kinds to get in the same bucket.

**Comment by sim642** [comment] 2023-02-22 12:06
Duplicate of #998 

The cause is very likely the same, but the description there is more detailed.

**Closed by sim642** 2023-02-22 12:06 UTC
Labels: bug
